import React,{useEffect,useState} from 'react';

const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
const empty={name:'',age:'',sex:'',phone:'',email:'',address:''};
async function api(path,opt={}){const r=await fetch(API+path,opt);if(!r.ok){const t=await r.text();throw new Error(t||'Request failed')}return r.json()}

function Card({children,className=''}){return <div className={'card '+className}>{children}</div>}
function Button({children,...p}){return <button className="btn" {...p}>{children}</button>}
function App(){
 const [tab,setTab]=useState('dashboard'),[patients,setPatients]=useState([]),[selected,setSelected]=useState(null),[dash,setDash]=useState(null),[msg,setMsg]=useState('');
 const load=async()=>{try{setPatients(await api('/api/patients'));setDash(await api('/api/dashboard'))}catch(e){setMsg('Backend not connected. Start FastAPI on port 8000.')}};
 useEffect(()=>{load()},[]);
 const openPatient=async id=>{setSelected(await api('/api/patients/'+id));setTab('patient')};
 return <div className="app">
  <aside><div className="brand"><div className="logo">M</div><div><b>MediKiosk</b><small>Clinical Intake Platform</small></div></div>
   {['dashboard','registration','interview','documents','analysis','doctor'].map(x=><button key={x} className={tab===x?'nav active':'nav'} onClick={()=>setTab(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}
   <div className="sidefoot">Secure workflow<br/>v1.0 MVP</div>
  </aside>
  <main><header><div><h1>{tab==='patient'?'Patient Record':tab[0].toUpperCase()+tab.slice(1)}</h1><p>Patient intake, document management and clinical decision support</p></div><span className="status">● API</span></header>
   {msg&&<div className="alert">{msg}</div>}
   {tab==='dashboard'&&<Dashboard dash={dash} patients={patients} open={openPatient}/>}
   {tab==='registration'&&<Registration onCreated={async p=>{await load();setSelected(await api('/api/patients/'+p.id));setTab('patient')}}/>}
   {tab==='interview'&&<Interview patients={patients} onDone={load}/>}
   {tab==='documents'&&<Documents patients={patients}/>}
   {tab==='analysis'&&<Analysis patients={patients} onOpen={openPatient}/>}
   {tab==='doctor'&&<Doctor patients={patients} onOpen={openPatient}/>}
   {tab==='patient'&&selected&&<PatientRecord data={selected} onBack={()=>setTab('dashboard')} onRefresh={()=>openPatient(selected.patient.id)}/>}
  </main>
 </div>
}

function Dashboard({dash,patients,open}){if(!dash)return <Card><p>Loading dashboard...</p></Card>;return <><div className="stats">{[['Patients',dash.stats.patients],['Interviews',dash.stats.interviews],['Documents',dash.stats.documents],['High Risk',dash.stats.high_risk]].map(([a,b])=><Card key={a}><small>{a}</small><strong>{b}</strong></Card>)}</div><Card><div className="row"><h2>Recent patients</h2><span>{patients.length} total</span></div><table><thead><tr><th>Code</th><th>Patient</th><th>Age</th><th>Risk</th><th></th></tr></thead><tbody>{dash.recent.map(p=><tr key={p.id}><td>{p.patient_code}</td><td>{p.name}</td><td>{p.age||'—'}</td><td><Risk v={p.risk_level}/></td><td><Button onClick={()=>open(p.id)}>Open</Button></td></tr>)}</tbody></table></Card></>}

function Registration({onCreated}){const [f,setF]=useState(empty),[busy,setBusy]=useState(false);const sub=async e=>{e.preventDefault();setBusy(true);try{const p=await api('/api/patients',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...f,age:f.age?Number(f.age):null})});setF(empty);await onCreated(p)}catch(e){alert(e.message)}finally{setBusy(false)}};return <Card><h2>Register new patient</h2><form onSubmit={sub}><div className="grid">{Object.keys(f).map(k=><label key={k}>{k}<input value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})} required={k==='name'} /></label>)}</div><Button disabled={busy}>{busy?'Saving...':'Create Patient'}</Button></form></Card>}

function Interview({patients,onDone}){const [id,setId]=useState(''),[f,setF]=useState({symptoms:'',duration:'',severity:'Moderate',history:'',medications:'',allergies:'',notes:''});const sub=async e=>{e.preventDefault();if(!id)return alert('Select a patient');try{await api('/api/interviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({patient_id:Number(id),...f})});alert('Interview saved');onDone()}catch(e){alert(e.message)}};return <Card><h2>Patient interview</h2><form onSubmit={sub}><label>Patient<select value={id} onChange={e=>setId(e.target.value)}><option value="">Select</option>{patients.map(p=><option value={p.id} key={p.id}>{p.patient_code} — {p.name}</option>)}</select></label><div className="grid"><label>Symptoms<textarea value={f.symptoms} onChange={e=>setF({...f,symptoms:e.target.value})} required/></label><label>Duration<input value={f.duration} onChange={e=>setF({...f,duration:e.target.value})}/></label><label>Severity<select value={f.severity} onChange={e=>setF({...f,severity:e.target.value})}><option>Low</option><option>Moderate</option><option>Severe</option></select></label><label>Medical history<textarea value={f.history} onChange={e=>setF({...f,history:e.target.value})}/></label><label>Medications<textarea value={f.medications} onChange={e=>setF({...f,medications:e.target.value})}/></label><label>Allergies<textarea value={f.allergies} onChange={e=>setF({...f,allergies:e.target.value})}/></label><label>Notes<textarea value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></label></div><Button>Save Interview</Button></form></Card>}

function Documents({patients}){const [id,setId]=useState(''),[file,setFile]=useState(null),[busy,setBusy]=useState(false);const sub=async e=>{e.preventDefault();if(!id||!file)return alert('Select patient and file');setBusy(true);const fd=new FormData();fd.append('patient_id',id);fd.append('file',file);try{await api('/api/documents/upload',{method:'POST',body:fd});alert('Document uploaded successfully');setFile(null);e.target.reset()}catch(e){alert(e.message)}finally{setBusy(false)}};return <Card><h2>Documents & OCR intake</h2><p className="muted">Upload reports, prescriptions, scans or other patient documents. The backend stores a SHA-256 integrity hash.</p><form onSubmit={sub}><label>Patient<select value={id} onChange={e=>setId(e.target.value)}><option value="">Select</option>{patients.map(p=><option value={p.id} key={p.id}>{p.patient_code} — {p.name}</option>)}</select></label><label>File<input type="file" onChange={e=>setFile(e.target.files[0])} accept=".pdf,.png,.jpg,.jpeg,.txt,.doc,.docx"/></label><Button disabled={busy}>{busy?'Uploading...':'Upload document'}</Button></form></Card>}

function Analysis({patients,onOpen}){const [id,setId]=useState(''),[res,setRes]=useState(null);const run=async()=>{if(!id)return;try{setRes(await api('/api/analysis',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({patient_id:Number(id)})}))}catch(e){alert(e.message)}};return <Card><h2>AI-assisted analysis</h2><p className="muted">This is screening support, not a medical diagnosis. A clinician must review the result.</p><label>Patient<select value={id} onChange={e=>setId(e.target.value)}><option value="">Select</option>{patients.map(p=><option value={p.id} key={p.id}>{p.patient_code} — {p.name}</option>)}</select></label><Button onClick={run}>Run analysis</Button>{res&&<div className="analysis"><div className="riskbox"><small>Risk level</small><strong><Risk v={res.risk_level}/></strong></div><h3>Summary</h3><p>{res.summary}</p><h3>Red flags</h3>{res.red_flags.length?<ul>{res.red_flags.map(x=><li key={x}>{x}</li>)}</ul>:<p>No automated red flags detected.</p>}<h3>Recommendations</h3><ul>{res.recommendations.map(x=><li key={x}>{x}</li>)}</ul><Button onClick={()=>onOpen(Number(id))}>Open patient record</Button></div>}</Card>}

function Doctor({patients,onOpen}){const [id,setId]=useState(''),[doctor,setDoctor]=useState(''),[decision,setDecision]=useState('Reviewed'),[notes,setNotes]=useState('');const save=async e=>{e.preventDefault();try{await api('/api/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({patient_id:Number(id),doctor,decision,notes})});alert('Review saved')}catch(e){alert(e.message)}};return <Card><h2>Doctor review</h2><form onSubmit={save}><label>Patient<select value={id} onChange={e=>setId(e.target.value)}><option value="">Select</option>{patients.map(p=><option value={p.id} key={p.id}>{p.patient_code} — {p.name}</option>)}</select></label><label>Doctor name<input value={doctor} onChange={e=>setDoctor(e.target.value)} required/></label><label>Decision<select value={decision} onChange={e=>setDecision(e.target.value)}><option>Reviewed</option><option>Needs follow-up</option><option>Urgent referral</option><option>Closed</option></select></label><label>Clinical notes<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><Button>Save review</Button></form>{id&&<Button onClick={()=>onOpen(Number(id))}>View patient record</Button>}</Card>}

function PatientRecord({data,onBack,onRefresh}){const p=data.patient,a=data.analyses[0],i=data.interviews[0];return <><Button onClick={onBack}>← Back</Button><div className="profile"><Card><small>Patient code</small><h2>{p.patient_code}</h2><p><b>{p.name}</b> · {p.age||'Age —'} · {p.sex||'Sex —'}</p><p>{p.phone||'No phone'} · {p.email||'No email'}</p><p>{p.address||'No address'}</p></Card><Card><small>Latest risk</small><h2><Risk v={a?.risk_level||'Not analyzed'}/></h2><p>{a?.summary||'No analysis yet.'}</p></Card></div><Card><h2>Latest interview</h2>{i?<><p><b>Symptoms:</b> {i.symptoms}</p><p><b>Duration:</b> {i.duration||'—'} · <b>Severity:</b> {i.severity}</p><p><b>History:</b> {i.history||'—'}</p><p><b>Medications:</b> {i.medications||'—'}</p><p><b>Allergies:</b> {i.allergies||'—'}</p></>:<p>No interview recorded.</p>}</Card><Card><h2>Documents</h2>{data.documents.length?data.documents.map(d=><div className="doc" key={d.id}><b>{d.filename}</b><span>{d.size} bytes · SHA256 {d.sha256.slice(0,16)}...</span></div>):<p>No documents uploaded.</p>}</Card><Card><h2>Doctor reviews</h2>{data.reviews.length?data.reviews.map(r=><div className="doc" key={r.id}><b>{r.doctor}</b><span>{r.decision} · {r.notes||'No notes'}</span></div>):<p>No review yet.</p>}</Card><Button onClick={onRefresh}>Refresh record</Button></>}

function Risk({v}){return <span className={'risk '+String(v||'').toLowerCase().replace(/\s/g,'-')}>{v||'—'}</span>}
export default App;
